dist: trusty
os: linux

language: node_js
node_js:
  - '10'

services: mongodb

cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  - npm test
  - codecov -f coverage/*.json
