dist: trusty
os: linux

language: node_js
node_js:
  - '10'

jdk: oraclejdk11

before_install:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.6.2-amd64.deb && sudo dpkg -i --force-confnew elasticsearch-7.6.2-amd64.deb && sudo chown -R elasticsearch:elasticsearch /etc/default/elasticsearch && sudo service elasticsearch restart

before_script:
  - sleep 10

services:
  - mongodb
  - redis-server
  - elasticsearch

cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  - npm test
  - codecov -f coverage/*.json
