redis:
  url: REDIS_CONNECTION_URL
  password: REDIS_CONNECTION_PASSWORD
  tls: REDIS_CONNECTION_TLS
  retry:
    secsWaitBetween: REDIS_CONNECTION_RETRY_WAIT
    secsAbortAfter: REDIS_CONNECTION_RETRY_ABORT
mongo:
  url: MONGO_CONNECTION_URL
  db: MONGO_DB_NAME
  collection: MONGO_COLLECTION_NAME
  driver:
    auto_reconnect: MONGO_AUTO_RECONNECT
  retry:
    secsWaitBetween: MONGO_CONNECTION_RETRY_WAIT
    secsAbortAfter: MONGO_CONNECTION_RETRY_ABORT
elastic:
  url: ELASTIC_CONNECTION_URL
  apiVersion: ELASTIC_API_VERSION
  index: ELASTIC_INDEX
  type: ELASTIC_TYPE
  retry:
    secsWaitBetween: ELASTIC_CONNECTION_RETRY_WAIT
    secsAbortAfter: ELASTIC_CONNECTION_RETRY_ABORT
