redis:
  url: redis://localhost:6379/0
  password: null
  tls: false
  retry:
    secsWaitBetween: 3
    secsAbortAfter: 300
mongo:
  url: mongodb://localhost:27017
  db: store
  collection: doc-store
  driver:
    auto_reconnect: false
  retry:
    secsWaitBetween: 3
    secsAbortAfter: 300
elastic:
  url: localhost:9200
  index: store
  apiVersion: "7.6"
  type: doc-store
  retry:
    secsWaitBetween: 3
    secsAbortAfter: 300
