store:
  redis:
    url: redis://localhost:6379/0
    password: null
    tls: false
    retry:
      secsWaitBetween: 3
      secsAbortAfter: 300
  mongo:
    url: mongodb://localhost:27017
  elastic:
    url: http://localhost:9001
